# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package



on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenJDK 17
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: connect server hemycoo8888
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            pwd   |
            echo "hello world" |
            whoami


      - name: Deploy JAR
        uses: horochx/deploy-via-scp@master
        with:
          local: './target/*.jar'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '~/app'
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}

      - name: 传输libs
        uses: horochx/deploy-via-scp@master
        with:
          local: './target/lib/*.jar'                                                  # Local file path - REQUIRED false - DEFAULT ./
          remote: '~/app/lib'
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}

      - name: 停止工程
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            pwd   |
            echo "hello world" |
            ps -ef | grep java |
            kill -9 QRcode-0.0.1.jar |
            echo "停止完成"

      - name: 启动工程
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            pwd   |
            echo "hello world" |
            cd ~/app |
            nohup java -jar QRcode-0.0.1.jar & |
            ps -ef | grep QRcode-0.0.1.jar |
            echo "启动完成"
